Repository UnBArqDsw2020-2/2020.2_G1_CabeleleiraLeila, pull requests merged in 2021-02, with the labels that each got.

#25 Prototipo de baixa fidelidade
  docs/base/prototipo-baixa.md
  docs/img/PROTÓTIPO DE BAIXA FIDELIDADE.pdf
  mkdocs.yml
Labels: documentation

#27 Adiciona Rich Picture
  docs/base/rich-picture.md
  docs/img/richpicture/richpicture1.jpg
  docs/img/richpicture/richpicture2.jpg
  docs/img/richpicture/richpicture3.1.png
  docs/img/richpicture/richpicture3.2.png
  docs/index.md
Labels: documentation, sprint 1

#26 Documentação do diagrama causa efeito
  docs/base/causa-efeito.md
  docs/img/diagrama-causa-efeito.jpg
Labels: documentation

#16 Mapa mental
  docs/base/5w2h.md
  docs/base/brainstorming.md
  docs/base/design-sprint.md
  docs/base/mapa-mental.md
  docs/img/base/mapa-mental.jpg
  docs/index.md
Labels: documentation

#15 5W2H
  docs/base/5w2h.md
  docs/base/brainstorming.md
  docs/index.md
Labels: documentation

#29 5w2h
  docs/base/5w2h.md
Labels: documentation

#31 Prototipo alta
  docs/base/entrevista.md
  docs/base/metodologia.md
  docs/base/protitipo-alta.md
  docs/base/teste-prototipo.md
  docs/img/teste1.jpg
  docs/img/teste2.jpg
  docs/img/teste3.jpg
  docs/img/teste4.jpg
Labels: documentation

#28 Adiciona plano de gerenciamento de riscos
  docs/base/brainstorming.md
  docs/base/plano-de-risco.md
  docs/img/diagrama-riscos.png
  mkdocs.yml
Labels: documentation

#34 Metodologia
  docs/base/metodologia.md
  docs/img/logos/logo.jpg
  mkdocs.yml
Labels: documentation

#33 Diagramas BPMN
  docs/base/bpmn.md
  docs/img/bpmn/bpmn-daily.png
  docs/img/bpmn/bpmn-desenvolvimento.png
  docs/img/bpmn/bpmn-metodologia-expandido.png
  docs/img/bpmn/bpmn-metodologia-geral.png
  docs/img/bpmn/bpmn-sprint-planning.png
  docs/img/bpmn/bpmn-sprint-review.png
  docs/index.md
  mkdocs.yml
Labels: documentation

#18 Design sprint
  docs/base/5w2h.md
  docs/base/design-sprint.md
Labels: documentation

#62 Diagrama agragacao composicao
  docs/img/modelagem/estatica/agregacao-composicao/diagramaAgregacaoComposicao.jpg
  docs/img/modelagem/estatica/agregacao-composicao/diagramaAgregacaoComposicao.svg
  docs/img/modelagem/estatica/agregacao-composicao/diagramaAgregacaoComposicao.xml
  docs/modelagem/agregacao-composicao.md
  mkdocs.yml
Labels: documentation, enhancement, sprint 3
