Repository UnBArqDsw2020-2/2020.2_G1_CabeleleiraLeila, pull requests merged in 2021-03, with the labels that each got.

#66 Reestruturação do doc Diagrama de Agregação e Composição
  docs/modelagem/agregacao-composicao.md
Labels: FIX, documentation, sprint 3

#71 Diagrama estados
  docs/base/diagrama-estados.md
  docs/img/diagrama-estado.jpg
  mkdocs.yml
Labels: documentation

#72 Refatora participantes
  docs/base/5w2h.md
  docs/base/backlog.md
  docs/base/bpmn.md
  docs/base/brainstorming.md
  docs/base/causa-efeito.md
  docs/base/design-sprint.md
  docs/base/entrevista.md
  docs/base/estimativas.md
  docs/base/identidade-visual.md
  docs/base/metodologia.md
  docs/base/moscow.md
  docs/base/plano-de-risco.md
  docs/base/prototipo-alta.md
  docs/base/prototipo-baixa.md
  docs/base/questionario.md
  docs/base/rich-picture.md
  docs/base/teste-prototipo.md
  docs/modelagem/agregacao-composicao.md
Labels: documentation

#68 Diagrama pacotes
  docs/img/modelagem/estatica/pacotes-backend.svg
  docs/modelagem/pacotes.md
  mkdocs.yml
Labels: documentation, sprint 4

#70 Diagrama classe
  dasdqawdq
  docs/img/modelagem/estatica/classes/classes_v1.jpg
  docs/img/modelagem/estatica/classes/classes_v2.svg
  docs/modelagem/classes.md
  mkdocs.yml
Labels: documentation, sprint 3

#75 Revisão do Diagrama de Pacotes e sugestão de mudanças
  docs/modelagem/pacotes.md
Labels: bug, documentation

#74 Casos uso
  docs/img/diagramas-casos-uso/diagramas-v1/uc01.png
  docs/img/diagramas-casos-uso/diagramas-v1/uc02.png
  docs/img/diagramas-casos-uso/diagramas-v1/uc03.png
  docs/img/diagramas-casos-uso/diagramas-v1/uc04.png
  docs/img/diagramas-casos-uso/diagramas-v1/uc05.png
  docs/img/diagramas-casos-uso/diagramas-v1/uc06.png
  docs/img/diagramas-casos-uso/diagramas-v1/uc07.png
  docs/img/diagramas-casos-uso/diagramas-v1/uc08.png
  docs/img/diagramas-casos-uso/diagramas-v1/uc09.png
  docs/img/diagramas-casos-uso/diagramas-v1/uc10.png
  docs/img/diagramas-casos-uso/diagramas-v1/uc11.png
  docs/img/diagramas-casos-uso/diagramas-v1/uc12.png
  docs/img/diagramas-casos-uso/diagramas-v1/uc13.png
  docs/img/diagramas-casos-uso/diagramas-v1/uc14.png
  docs/img/diagramas-casos-uso/diagramas-v1/uc15.png
  docs/img/diagramas-casos-uso/diagramas-v1/uc16.png
  docs/img/diagramas-casos-uso/diagramas-v2/UC01.png
  docs/img/diagramas-casos-uso/diagramas-v2/UC02.png
  docs/img/diagramas-casos-uso/diagramas-v2/UC03.png
  docs/img/diagramas-casos-uso/diagramas-v2/UC04.png
  docs/img/diagramas-casos-uso/diagramas-v2/UC05.png
  docs/img/diagramas-casos-uso/diagramas-v2/UC06.png
  docs/modelagem/diagrama-casos-uso.md
  docs/modelagem/diagramas-casos-uso/diagramas-v1/uc01.md
  docs/modelagem/diagramas-casos-uso/diagramas-v1/uc02.md
  docs/modelagem/diagramas-casos-uso/diagramas-v1/uc03.md
  docs/modelagem/diagramas-casos-uso/diagramas-v1/uc04.md
  docs/modelagem/diagramas-casos-uso/diagramas-v1/uc05.md
  docs/modelagem/diagramas-casos-uso/diagramas-v1/uc06.md
  docs/modelagem/diagramas-casos-uso/diagramas-v1/uc07.md
  docs/modelagem/diagramas-casos-uso/diagramas-v1/uc08.md
  docs/modelagem/diagramas-casos-uso/diagramas-v1/uc09.md
  docs/modelagem/diagramas-casos-uso/diagramas-v1/uc10.md
  docs/modelagem/diagramas-casos-uso/diagramas-v1/uc11.md
  docs/modelagem/diagramas-casos-uso/diagramas-v1/uc12.md
  docs/modelagem/diagramas-casos-uso/diagramas-v1/uc13.md
  docs/modelagem/diagramas-casos-uso/diagramas-v1/uc14.md
  docs/modelagem/diagramas-casos-uso/diagramas-v1/uc15.md
  docs/modelagem/diagramas-casos-uso/diagramas-v1/uc16.md
  docs/modelagem/diagramas-casos-uso/diagramas-v2/uc01.md
  docs/modelagem/diagramas-casos-uso/diagramas-v2/uc02.md
  docs/modelagem/diagramas-casos-uso/diagramas-v2/uc03.md
  docs/modelagem/diagramas-casos-uso/diagramas-v2/uc04.md
  docs/modelagem/diagramas-casos-uso/diagramas-v2/uc05.md
  docs/modelagem/diagramas-casos-uso/diagramas-v2/uc06.md
  mkdocs.yml
Labels: documentation, sprint 4

#81 Diagrama sequencia
  docs/img/diagrama_sequencia/diagrama-sequencia01.png
  docs/img/diagrama_sequencia/diagrama-sequencia02.png
  docs/img/diagrama_sequencia/diagrama-sequencia03.png
  docs/img/diagrama_sequencia/diagrama-sequencia04.png
  docs/img/diagrama_sequencia/diagrama-sequencia05.png
  docs/img/diagrama_sequencia/diagrama-sequencia06.png
  docs/img/diagrama_sequencia/diagrama-sequencia07.png
  docs/img/diagrama_sequencia/diagrama-sequencia08.png
  docs/modelagem/diagrama-sequencia.md
  mkdocs.yml
Labels: sprint 4

#73 Diagrama componentes
  docs/img/diagrama-componentes.png
  docs/img/legendas_elementos.png
  docs/modelagem/diagrama-componentes.md
  docs/modelagem/diagrama_atividades.md
  mkdocs.yml
Labels: documentation, sprint 4

#76 Finalizando o Backlog
  docs/base/backlog.md
  docs/img/elicitacao/.DS_Store
  docs/img/elicitacao/backlog2.png
  docs/img/elicitacao/legenda.png
Labels: documentation, sprint 4

#80 Diagrama relacional
  docs/img/modelagem/dinamica/der-dld/der.jpg
  docs/img/modelagem/dinamica/der-dld/derLeila.brM3
  docs/img/modelagem/dinamica/der-dld/dld.jpg
  docs/img/modelagem/dinamica/der-dld/dldLeila.brM3
  docs/modelagem/diagrama-relacional.md
  mkdocs.yml
Labels: documentation, sprint 4
